export const COLORS = {
  PRIMARY: "#000",
  PRIMARY_LIGHT: "#333",
  SECONDARY: "#666",
  ACCENT: "#999",

  BACKGROUND: "#fff",
  BACKGROUND_SECONDARY: "#f8f8f8",
  BACKGROUND_TERTIARY: "#f5f5f5",
  BACKGROUND_QUATERNARY: "#f0f0f0",

  BORDER: "#eee",
  BORDER_LIGHT: "#e0e0e0",
  BORDER_DARK: "#ccc",

  TEXT_PRIMARY: "#000",
  TEXT_SECONDARY: "#333",
  TEXT_TERTIARY: "#666",
  TEXT_LIGHT: "#999",
  TEXT_ON_DARK: "#fff",

  SHADOW: "#000",

  SUCCESS: "#7ED321",
  WARNING: "#F5A623",
  ERROR: "#FF6B6B",
  INFO: "#4A90E2",

  TAB_ACTIVE: "#000",
  TAB_INACTIVE: "#999",

  ICON_PRIMARY: "#000",
  ICON_SECONDARY: "#666",

  TAG_BACKGROUND: "#f5f5f5",
  TAG_TEXT: "#666",
  TAG_ACTIVE_BACKGROUND: "#000",
  TAG_ACTIVE_TEXT: "#fff",

  CARD_BACKGROUND: "#fff",
  CARD_BORDER: "#f0f0f0",
  CARD_SHADOW: "#000",

  DROPDOWN_BACKGROUND: "#f8f8f8",
  DROPDOWN_BORDER: "#e0e0e0",
  DROPDOWN_ACTIVE_BACKGROUND: "#000",
  DROPDOWN_ACTIVE_BORDER: "#000",
  DROPDOWN_TEXT: "#666",
  DROPDOWN_ACTIVE_TEXT: "#fff",
  DROPDOWN_ITEM_BORDER: "#f0f0f0",

  COLLAGE_BACKGROUND: "#f8f8f8",
} as const;
